# ✅ GitLab CI/CD - Manual Infrastructure Deployment for Azure
workflow:
  rules:
    - when: manual  # 🔥 Ensures manual execution

include:
  - local: ".gitlab-ci/stages/deploy-azure.yml"  # ✅ Includes reusable deployment stage

variables:
  AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID
  AZURE_CLIENT_ID: $AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
  AZURE_TENANT_ID: $AZURE_TENANT_ID
  AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
  AZURE_REGION: "eastus"

stages:
  - deploy-infrastructure

deploy-azure-infrastructure:
  extends: .deploy-azure  # ✅ Calls the external job
  stage: deploy-infrastructure
