# ========================================
# GitLab CI/CD - Manual Infra Deployment (Azure Bicep)
# ========================================
stages:
  - deploy

# ðŸ”¥ Manual trigger only
infra-deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:2.60.0
  rules:
    - when: manual
  variables:
    # -----------------------------
    # Parameters (override in CI/CD UI or group vars)
    # -----------------------------
    DATABASE_TYPE: "single"          # [single, multi]
    EVENT_STORAGE_TYPE: "Kafka"      # [Kafka, CosmosDB, MongoDB]
    ENTITY_STORAGE_TYPE: "SQLServer" # [PostgreSQL, MariaDB, MySQL, SQLServer, Oracle]
    MESSAGING_TYPE: "Kafka"          # [Kafka, RabbitMQ, Both, None]
    ENVIRONMENT: "dev"               # [dev, staging, prod]
    CONTAINER_IMAGE: ""              # injected from build pipeline
    RESOURCE_GROUP: "$AZURE_RESOURCE_GROUP"
    AZURE_SUBSCRIPTION: "$AZURE_SUBSCRIPTION_ID"

  script:
    # ðŸ”‘ (Optional) Fetch secret from Key Vault
    - echo "ðŸ”‘ Fetching DB Secret..."
    - |
      if [ -n "$KEYVAULT_NAME" ]; then
        DB_CONNECTION_STRING=$(az keyvault secret show \
          --name DBConnectionString \
          --vault-name "$KEYVAULT_NAME" \
          --query value -o tsv)
        export DB_CONNECTION_STRING
      fi

    # ðŸš€ Deploy Bicep
    - echo "===================================="
    - echo "ðŸŒ Env:       $ENVIRONMENT"
    - echo "ðŸ—„ï¸ DB:        $DATABASE_TYPE"
    - echo "ðŸ“‚ Event:     $EVENT_STORAGE_TYPE"
    - echo "ðŸ“‚ Entity:    $ENTITY_STORAGE_TYPE"
    - echo "ðŸ“© Messaging: $MESSAGING_TYPE"
    - echo "ðŸ³ Image:     $CONTAINER_IMAGE"
    - echo "===================================="

    - az account set --subscription "$AZURE_SUBSCRIPTION"
    - |
      az deployment group create \
        --resource-group "$RESOURCE_GROUP" \
        --name main-$ENVIRONMENT \
        --template-file main.bicep \
        --mode Incremental \
        --only-show-errors \
        --parameters \
          databaseType=$DATABASE_TYPE \
          eventStorageType=$EVENT_STORAGE_TYPE \
          entityStorageType=$ENTITY_STORAGE_TYPE \
          messagingType=$MESSAGING_TYPE \
          environment=$ENVIRONMENT \
          containerImage=$CONTAINER_IMAGE \
          DBConnectionString="$DB_CONNECTION_STRING"

    # ðŸ“¤ Capture Outputs
    - echo "ðŸ“¤ Capturing Bicep Outputs..."
    - |
      outputs=$(az deployment group show \
        -g "$RESOURCE_GROUP" \
        -n main-$ENVIRONMENT \
        --query properties.outputs -o json)

      echo "ðŸ”Ž Raw Outputs: $outputs"
      echo "$outputs" > infra-outputs.json

  artifacts:
    name: "infra-outputs-$ENVIRONMENT"
    paths:
      - infra-outputs.json
    expire_in: 7 days
