stages:
  - build
  - deploy

# ========================================
# âœ… Variables (override in GitLab CI/CD settings)
# ========================================
variables:
  GCP_PROJECT_ID: "my-gcp-project"
  GCP_REGION: "us-central1"
  IMAGE_TAG: "$CI_PIPELINE_IID"
  REPOSITORY: "Franz"
  SERVICE_NAME: "microservice"
  GCP_ARTIFACT_REGISTRY: "us-central1-docker.pkg.dev/my-gcp-project/my-repo"
  DEPLOY_TO_GKE: "false"  # set to "true" for GKE deploy

# ========================================
# ðŸ”¨ Build & Push Docker Image
# ========================================
build-and-push:
  stage: build
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  services:
    - docker:dind
  script:
    - echo "$GCLOUD_SERVICE_KEY" | base64 -d > $CI_PROJECT_DIR/gcloud.json
    - gcloud auth activate-service-account --key-file=gcloud.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

    - IMAGE="$GCP_ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG"
    - echo "ðŸ³ Building image: $IMAGE"
    - docker build -t $IMAGE .
    - docker push $IMAGE

    # save image tag for deploy stage
    - echo "DEPLOY_IMAGE=$IMAGE" >> build.env
  artifacts:
    reports:
      dotenv: build.env

# ========================================
# ðŸš€ Deploy to GKE
# ========================================
deploy-gke:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  needs: ["build-and-push"]
  rules:
    - if: '$DEPLOY_TO_GKE == "true"'
  script:
    - echo "$GCLOUD_SERVICE_KEY" | base64 -d > $CI_PROJECT_DIR/gcloud.json
    - gcloud auth activate-service-account --key-file=gcloud.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials gke-$REPOSITORY-cluster --region $GCP_REGION

    - echo "ðŸš€ Deploying to GKE image: $DEPLOY_IMAGE"
    - kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$DEPLOY_IMAGE
    - kubectl rollout status deployment/$SERVICE_NAME

# ========================================
# ðŸš€ Deploy to Cloud Run
# ========================================
deploy-cloudrun:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  needs: ["build-and-push"]
  rules:
    - if: '$DEPLOY_TO_GKE == "false"'
  script:
    - echo "$GCLOUD_SERVICE_KEY" | base64 -d > $CI_PROJECT_DIR/gcloud.json
    - gcloud auth activate-service-account --key-file=gcloud.json
    - gcloud config set project $GCP_PROJECT_ID

    - echo "ðŸš€ Deploying to Cloud Run image: $DEPLOY_IMAGE"
    - gcloud run deploy $SERVICE_NAME \
        --image=$DEPLOY_IMAGE \
        --region=$GCP_REGION \
        --platform=managed \
        --allow-unauthenticated
