jobs:
- job: docker-build
  displayName: "Docker Build & Push"
  dependsOn: terraform-apply
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - checkout: self

    - task: Docker@2
      displayName: "Login to AWS ECR"
      inputs:
        command: login
        containerRegistry: "$(awsEcrRegistry)"

    - task: Docker@2
      displayName: "Build Docker Image"
      inputs:
        command: build
        repository: "${{ parameters.repository }}"
        dockerfile: "sources/back/Franz.Api/Dockerfile"
        buildContext: "sources/back/Franz.Api"
        tags: |
          $(Build.SourceVersion)
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: "Push Docker Image to AWS ECR"
      inputs:
        command: push
        repository: "${{ parameters.repository }}"
        tags: |
          $(Build.SourceVersion)
          $(Build.BuildId)
          latest

    - script: |
        echo "{ \"image\": \"$(awsEcrRegistry)/${{ parameters.repository }}:$(Build.BuildId)\" }" > image-info.json
      displayName: "Save image info"

    - publish: image-info.json
      artifact: image-tag
