parameters:
  projectName: 'TestFranz'
  environmentName: ''
  azureServiceConnection: ''
  resourceGroupName: ''
  resourceGroupLocation: ''
  applicationVersion: ''
  repositoryName: ''
  languages: ''
  mutualizeOpenAI: ''
  registrerPAL: ''
  actionGroupName: 'Health Check Action Group'

jobs:
- deployment: Deploy
  environment: ${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-latest'
  
  variables:
    - group: franz-${{ parameters.environmentName }}
    - group: mutualized-resources
    - name: templateFile
      value: '$(Build.SourcesDirectory)/infrastructure/main.bicep'
    - name: templateParametersFile
      value: '$(Build.SourcesDirectory)/infrastructure/parameters/${{ parameters.environmentName }}.parameters.json'

  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
              
        # Step 1: Check if Action Group Exists
        - task: AzureCLI@2
          displayName: 'Check if ${{ parameters.actionGroupName }} Exists'
          inputs:
            azureSubscription:  ${{ parameters.azureServiceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
                if az monitor action-group show --name '${{ parameters.actionGroupName }}' --resource-group '${{ parameters.resourceGroupName }}'; then
                    echo "The ${{ parameters.actionGroupName }} exists."
                    echo "##vso[task.setvariable variable=actionGroupExists;isOutput=true]true"
                else
                    echo "The ${{ parameters.actionGroupName }} does not exist."
                    echo "##vso[task.setvariable variable=actionGroupExists;isOutput=true]false"
                fi
          name: CheckActionGroup

        # Step 2: Deploy Infrastructure using Bicep
        - task: AzureCLI@2
          displayName: "Deploy Infrastructure with Bicep"
          inputs:
            azureSubscription:  ${{ parameters.azureServiceConnection }}
            scriptType: bash 
            scriptLocation: inlineScript
            inlineScript: |
              az config set bicep.use_binary_from_path=false
              az deployment group create \
                --resource-group ${{ parameters.resourceGroupName }} \
                --template-file $(templateFile) \
                --mode Incremental \
                --parameters $(templateParametersFile) \
                --parameters \
                  projectShortName="${{ parameters.projectName }}" \
                  environmentShortName="${{ parameters.environmentName }}" \
                  frontendClientId="$(frontendClientId)" \
                  frontendClientSecret="$(frontendClientSecret)" \
                  containerRegistryPassword="$(ContainerRegistryPassword)" \
                  developpersAdGroupId="$(developpersAdGroupId)" \
                  mutualizeOpenAI="${{ parameters.mutualizeOpenAI }}" \
                  existingOpenAiEndpoint="$(existingOpenAiEndpoint)" \
                  bingSearchApiKey="$(bingSearchApiKey)" \
                  frontendApplicationVersion="${{ parameters.repositoryName }}-frontend:${{ parameters.applicationVersion }}" \
                  actionGroupExists="$(CheckActionGroup.actionGroupExists)" \
                  actionGroupName="${{ parameters.actionGroupName }}"

        # Step 3: Capture BICEP Outputs as Agent Variables
        - task: AzureCLI@2
          displayName: "Capture BICEP Outputs as Agent Variables"
          name: 'bicepOutput'
          inputs:
            azureSubscription:  ${{ parameters.azureServiceConnection }}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              $out = az deployment group show -g ${{ parameters.resourceGroupName }} -n main | convertfrom-json | foreach properties | foreach outputs

              $provisionOutputs = [PSCustomObject]@{}
              $out | Get-Member -MemberType NoteProperty | ForEach-Object {

                  $name = $_.name
                  $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
                  Write-Host "##vso[task.setvariable variable=$($name);isOutput=true]$($out.$name.value)"
              }

              $provisionOutputs

        # Step 4: Restart Web App (Optional)
        - task: AzureCLI@2
          displayName: "Restart Web App"
          inputs:
            azureSubscription:  ${{ parameters.azureServiceConnection }}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az webapp restart --name $(bicepOutput.frontEndServiceName) --resource-group ${{ parameters.resourceGroupName }}

        # Step 5: PAL Registration (Conditional)
        - task: AzureCLI@2
          condition: ${{ parameters.registrerPAL }}
          displayName: "Run PowerShell Script for PAL Registration"
          inputs:
            azureSubscription:  ${{ parameters.azureServiceConnection }}
            scriptType: 'pscore'
            scriptLocation: 'scriptPath'
            scriptPath: 'pipelines/powershellScripts/savePAL.ps1'
