parameters:
  repository: ''
  workdir: ''
  registry: ''
  dockerfile: ''
  version: ''

jobs:
- job: Publish
  displayName: 'Publish Docker Image'
  pool:
      vmImage: 'ubuntu-latest'
        
  steps:
    # Step 1: Login to the Azure Container Registry
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login 
        containerRegistry: ${{ parameters.registry }}

    # Step 2: Build the Docker image
    - task: Docker@2
      displayName: 'Build Docker image and push to ACR'
      inputs:
        command: buildAndPush
        repository: ${{ parameters.repository }}
        containerRegistry: ${{ parameters.registry }}
        dockerfile: ${{ parameters.dockerfile }}
        buildContext: ${{ parameters.workdir }}
        tags: |
          ${{ parameters.version }}
