# ✅ GitLab CI/CD - Deploy Infra with Built Image (Bicep)
stages:
  - deploy

deploy-azure-infra:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:2.59.0  # ✅ Azure CLI Docker image
  variables:
    PROJECT_NAME: "TestFranz"
    ENVIRONMENT_NAME: "dev"       # override per-job or in GitLab UI
    RESOURCE_GROUP_NAME: "my-rg"
    RESOURCE_GROUP_LOCATION: "eastus"
    APPLICATION_VERSION: "1.0.0"
    REPOSITORY_NAME: "franz-repo"
    LANGUAGES: "dotnet"
    MUTUALIZE_OPENAI: "false"
    REGISTRER_PAL: "false"
    MESSAGING_TYPE: "Kafka"
    ACTION_GROUP_NAME: "Health Check Action Group"
    # 👇 Secrets injected via GitLab CI/CD variables
    AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID
    AZURE_CLIENT_ID: $AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
    AZURE_TENANT_ID: $AZURE_TENANT_ID

  script:
    # 🔽 Download artifact containing image tag
    - echo "🔽 Downloading docker-image-info artifact"
    - mkdir -p artifacts
    - curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/docker-image-info/image-info.json?job=build" \
           --output artifacts/image-info.json

    # 📤 Extract Image Tag
    - IMAGE_TAG=$(jq -r .image artifacts/image-info.json)
    - echo "Using image tag: $IMAGE_TAG"

    # 🔑 Login to Azure
    - az login --service-principal \
        -u $AZURE_CLIENT_ID \
        -p $AZURE_CLIENT_SECRET \
        --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID

    # 🚀 Deploy Bicep
    - az deployment group create \
        --resource-group $RESOURCE_GROUP_NAME \
        --name main-$ENVIRONMENT_NAME \
        --template-file Infrastructure/AzureDevOps-Bicep/main.bicep \
        --mode Incremental \
        --only-show-errors \
        --parameters \
          projectShortName=$PROJECT_NAME \
          environmentShortName=$ENVIRONMENT_NAME \
          containerImage=$IMAGE_TAG \
          messagingType=$MESSAGING_TYPE
          
  artifacts:
    paths:
      - artifacts/image-info.json
    expire_in: 7 days
