# âœ… GitLab CI/CD - Build & Publish Docker Image
stages:
  - build
  - publish

docker-build-publish:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind  # Docker-in-Docker service
  variables:
    DOCKER_TLS_CERTDIR: ""   # required for docker:dind
    REPOSITORY: "my-repo/app"        # override in GitLab CI/CD variables
    WORKDIR: "."                       # where Dockerfile lives
    REGISTRY: "$CI_REGISTRY"          # GitLab registry by default
    DOCKERFILE: "Dockerfile"
    VERSION: "1.0.0"                   # usually $CI_COMMIT_TAG or $CI_COMMIT_SHORT_SHA
  script:
    # ðŸ”‘ Login to registry
    - echo "ðŸ”‘ Logging in to $REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

    # ðŸ³ Build & push Docker image
    - echo "ðŸ³ Building & pushing Docker image..."
    - docker build -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:$VERSION -t $REGISTRY/$REPOSITORY:latest $WORKDIR
    - docker push $REGISTRY/$REPOSITORY:$VERSION
    - docker push $REGISTRY/$REPOSITORY:latest

    # ðŸ“¤ Save Image Tag for downstream jobs
    - echo "{\"image\": \"$REGISTRY/$REPOSITORY:$VERSION\"}" > image-info.json
    - cat image-info.json

  artifacts:
    paths:
      - image-info.json
    name: docker-image-info
    expire_in: 7 days
