stages:
  - infra

variables:
  TF_VERSION: "1.9.6"
  DEPLOY_TARGET: "eks"   # or ecs, passed at run time

terraform-init:
  stage: infra
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - cd infrastructure/Terraform-AWS/$DEPLOY_TARGET
    - terraform init -input=false
  artifacts:
    paths:
      - infrastructure/Terraform-AWS/$DEPLOY_TARGET/.terraform
    expire_in: 1h

terraform-validate:
  stage: infra
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - cd infrastructure/Terraform-AWS/$DEPLOY_TARGET
    - terraform validate
    - terraform fmt -check -recursive

terraform-plan:
  stage: infra
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - cd infrastructure/Terraform-AWS/$DEPLOY_TARGET
    - terraform plan -out=tfplan
    - terraform show -json tfplan > plan.json
  artifacts:
    paths:
      - infrastructure/Terraform-AWS/$DEPLOY_TARGET/tfplan
      - infrastructure/Terraform-AWS/$DEPLOY_TARGET/plan.json
    expire_in: 1 week

terraform-apply:
  stage: infra
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - cd infrastructure/Terraform-AWS/$DEPLOY_TARGET
    - terraform apply -input=false tfplan
  dependencies:
    - terraform-plan
  when: manual
