stages:
  - docker

docker-build-push:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    AWS_REGION: "eu-west-1"
    IMAGE_NAME: "myapp"
  before_script:
    - apk add --no-cache python3 py3-pip jq
    - pip3 install awscli
    - echo "ðŸ” Logging into AWS ECR..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  script:
    - IMAGE_TAG=${CI_COMMIT_SHORT_SHA}
    - FULL_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG"
    - echo "ðŸ³ Building image $FULL_IMAGE"
    - docker build -t $FULL_IMAGE -f Dockerfile .
    - docker push $FULL_IMAGE
    - echo "{\"image\":\"$FULL_IMAGE\"}" > image-info.json
  artifacts:
    paths:
      - image-info.json
    expire_in: 1 week
