# azure-pipelines.yml
# Pipeline triggered by commits to the 'develop' branch

# 1. Trigger: Switch from 'trigger: none' to specifying the branch
trigger:
  branches:
    include:
      - develop  # ✅ The pipeline will now run on every commit to 'develop'
pr: none         # Still prevents running on Pull Request creation

# 2. Agent/Runner: Use a Microsoft-hosted Windows Agent
pool:
  vmImage: 'windows-latest'

# 3. Variables
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# 4. Jobs and Steps
jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'

  steps:
  
  # ------------------ Restore Dependencies (NuGet) ------------------
  - task: DotNetCoreCLI@2
    displayName: '1. NuGet Restore'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  # ------------------ Build Solution ------------------
  - task: DotNetCoreCLI@2
    displayName: '2. Build Solution'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '/p:Platform="$(buildPlatform)" /p:Configuration="$(buildConfiguration)"'

  # ------------------ Run Automated Tests ------------------
  - task: DotNetCoreCLI@2
    displayName: '3. Run Automated Tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) --no-build'

