# ❌ Prevent Auto-Triggers
pr: none
trigger: none  # 🔥 Ensures the pipeline is only triggered manually

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'  # Solution files to be restored
  buildPlatform: 'Any CPU'  # Platform for building
  buildConfiguration: 'Release'  # Build configuration

jobs:
  - job: BuildAndTest
    displayName: 'Build, Test and Docker Build'
    steps:
      # Step 1: Install NuGet tool
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool Installer'

      # Step 2: Restore NuGet Packages
      - task: NuGetCommand@2
        displayName: 'Restore NuGet Packages'
        inputs:
          restoreSolution: '$(solution)'
          feedsToUse: 'config'
          nugetConfigPath: 'nuget.config'

      # Step 3: Build the Solution
      - task: VSBuild@1
        displayName: 'Build the Solution'
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:ExcludeProjects="**/Franz.DockerCompose/Franz.DockerCompose.dcproj"'

      # Step 4: Run Automated Tests
      - task: VSTest@2
        displayName: 'Run Automated Tests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
