# ✅ Prevent Auto-Triggers
pr: none
trigger: none  # Ensures the pipeline is only run manually

parameters:
  - name: databaseType
    displayName: "Database Type"
    type: string
    default: "single"
    values:
      - single
      - multi

  - name: eventStorageType
    displayName: "Event Storage Type (Only for Multi-DB)"
    type: string
    default: "Kafka"
    values:
      - Kafka
      - CosmosDB
      - MongoDB

  - name: entityStorageType
    displayName: "Entity Storage Type"
    type: string
    default: "SQLServer"
    values:
      - PostgreSQL
      - MariaDB
      - MySQL
      - SQLServer
      - Oracle

variables:
  - group: DevVariables  # ✅ Link to environment-specific variables

jobs:
- job: Deploy
  displayName: "Manual Infrastructure Deployment"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: AzureCLI@2
      displayName: "Fetch Secrets from Azure Key Vault"
      inputs:
        azureSubscription: 'your-azure-subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Fetching database connection string..."
          DB_CONNECTION_STRING=$(az keyvault secret show --name DBConnectionString --vault-name $(keyVaultName) --query value -o tsv)
          echo "##vso[task.setvariable variable=DB_CONNECTION_STRING]$DB_CONNECTION_STRING"

    - task: AzureCLI@2
      displayName: "Deploy Infrastructure"
      inputs:
        azureSubscription: 'your-azure-subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Starting deployment with database mode: ${{ parameters.databaseType }}"
          
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file main.bicep \
            --parameters databaseType=${{ parameters.databaseType }} \
                         eventStorageType=${{ parameters.eventStorageType }} \
                         entityStorageType=${{ parameters.entityStorageType }} \
                         environment=dev \
                         DBConnectionString=$(DB_CONNECTION_STRING)
