trigger:
- main

variables:
  - group: DevVariables  # Link to your environment-specific variable group

jobs:
- job: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'your-azure-subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Fetch secret from Azure Key Vault
          DB_CONNECTION_STRING=$(az keyvault secret show --name DBConnectionString --vault-name $(keyVaultName) --query value -o tsv)
          
          # Deploy to Azure using the secrets and environment-specific parameters
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file main.bicep \
            --parameters frontEndType=$(frontEndType) \
                         databaseType=$(databaseType) \
                         eventStorageType=$(eventStorageType) \
                         entityStorageType=$(entityStorageType) \
                         environment=dev \
                         DBConnectionString=$DB_CONNECTION_STRING
