trigger:
  branches:
    include:
      - main  # Adjust this based on your branch strategy

parameters:
  - name: repository
    displayName: Repository name
    default: Franz
  - name: major
    displayName: Major {x.0.0}
    type: number
    default: 2
  - name: minor
    displayName: Minor {1.x.0}
    type: number
    default: 1
  - name: patch
    displayName: Patch {1.0.x}
    type: string
    default: 5
  - name: frontEndType
    displayName: "Front-End Type"
    type: string
    default: "Blazor"
    values:
      - Angular
      - Blazor
      - ASP.NET

variables:
  frontendPaths:
    Angular: 
      dockerfilePath: 'src/FranzFront.Angular/Dockerfile'
      buildContext: 'src/FranzFront.Angular'
    Blazor: 
      dockerfilePath: 'src/FranzFront.Blazor/Client/Dockerfile'
      buildContext: 'src/FranzFront.Blazor'
    ASP.NET: 
      dockerfilePath: 'src/FranzFront.ASPNET/Dockerfile'
      buildContext: 'src/FranzFront.ASPNET'

  dockerfilePath: $[variables['frontendPaths'][parameters.frontEndType].dockerfilePath]
  buildContext: $[variables['frontendPaths'][parameters.frontEndType].buildContext]

stages:
- stage: "Build_Frontend"
  displayName: "Build Frontend"
  jobs:
    - job: DockerBuildFrontend
      displayName: "Docker Build Frontend"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: 'Build Docker image for selected front-end'
          inputs:
            containerRegistry: 'gpt4enterprisesharedacr-connection'
            repository: '${{ parameters.repository }}-frontend-${{ parameters.frontEndType }}'
            dockerfile: ${{ variables.dockerfilePath }}
            buildContext: ${{ variables.buildContext }}
            tags: |
              ${{ parameters.Major }}.${{ parameters.Minor }}.${{ parameters.patch }}

- stage: "Build_Backend"
  displayName: "Build Backend"
  jobs:
    - job: DockerBuildBackend
      displayName: "Docker Build Backend"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: 'Build Docker image for API'
          inputs:
            containerRegistry: 'gpt4enterprisesharedacr-connection'
            repository: '${{ parameters.repository }}-api'
            dockerfile: 'src/Franz.Backend/Api/Dockerfile'
            buildContext: 'src/Franz.Backend/Api'
            tags: |
              ${{ parameters.Major }}.${{ parameters.Minor }}.${{ parameters.patch }}

        - task: Docker@2
          displayName: 'Build Docker image for Consumer'
          inputs:
            containerRegistry: 'gpt4enterprisesharedacr-connection'
            repository: '${{ parameters.repository }}-consumer'
            dockerfile: 'src/Franz.Backend/Consumer/Dockerfile'
            buildContext: 'src/Franz.Backend/Consumer'
            tags: |
              ${{ parameters.Major }}.${{ parameters.Minor }}.${{ parameters.patch }}

- stage: "Deploy_Infrastructure"
  displayName: "Deploy Infrastructure"
  jobs:
    - job: 
      displayName: "Deploy Infrastructure with Bicep"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureCLI@2
          displayName: 'Deploy infrastructure using Bicep'
          inputs:
            azureSubscription: ''
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az config set bicep.use_binary_from_path=false
              az deployment group create \
                --resource-group ${{ parameters.resourceGroupName }} \
                --template-file src/infrastructure/main.bicep \
                --parameters frontendClientId="$(frontendClientId)" \
                --parameters backendClientId="$(backendClientId)" \
                --mode Incremental
