pr: none  # ❌ Prevent auto-trigger on pull requests
trigger: none  # ❌ Ensure manual execution

parameters:
  - name: repository
    displayName: Repository Name
    default: Franz
  - name: major
    displayName: Major Version {x.0.0}
    type: number
    default: 2
  - name: minor
    displayName: Minor Version {1.x.0}
    type: number
    default: 1
  - name: patch
    displayName: Patch Version {1.0.x}
    type: string
    default: 5
  - name: frontEndType
    displayName: "Front-End Type"
    type: string
    default: "Blazor"
    values:
      - Angular
      - Blazor
      - ASP.NET

variables:
  - group: "Azure Variables"  # ✅ Load environment-specific variables

stages:
# ========================================
# ✅ BUILD FRONTEND STAGE
# ========================================
- stage: "Build_Frontend"
  displayName: "Build Frontend"
  jobs:
    - job: DockerBuildFrontend
      displayName: "Docker Build Frontend"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: |
            if [ "${{ parameters.frontEndType }}" == "Angular" ]; then
              echo "##vso[task.setvariable variable=dockerfilePath]sources/front/FranzFront.Angular/Dockerfile"
              echo "##vso[task.setvariable variable=buildContext]sources/front/FranzFront.Angular"
            elif [ "${{ parameters.frontEndType }}" == "Blazor" ]; then
              echo "##vso[task.setvariable variable=dockerfilePath]sources/front/FranzFront.Blazor/Client/Dockerfile"
              echo "##vso[task.setvariable variable=buildContext]sources/front/FranzFront.Blazor"
            else
              echo "##vso[task.setvariable variable=dockerfilePath]sources/front/FranzFront.ASPNET/Dockerfile"
              echo "##vso[task.setvariable variable=buildContext]sources/front/FranzFront.ASPNET"
            fi
          displayName: "Set Docker Build Context Variables"

        - task: Docker@2
          displayName: "Build Docker image for selected front-end"
          inputs:
            containerRegistry: $(AZURE_CONTAINER_REGISTRY)
            repository: "${{ parameters.repository }}-frontend-${{ parameters.frontEndType }}"
            dockerfile: "$(dockerfilePath)"
            buildContext: "$(buildContext)"
            tags: |
              ${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}

# ========================================
# ✅ BUILD BACKEND STAGE
# ========================================
- stage: "Build_Backend"
  displayName: "Build Backend"
  jobs:
    - job: DockerBuildBackend
      displayName: "Docker Build Backend"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: "Build Docker image for API"
          inputs:
            containerRegistry: $(AZURE_CONTAINER_REGISTRY)
            repository: "${{ parameters.repository }}-api"
            dockerfile: "sources/back/Franz.Api/Dockerfile"
            buildContext: "sources/back/Franz.Api"
            tags: |
              ${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}

        - task: Docker@2
          displayName: "Build Docker image for Consumer"
          inputs:
            containerRegistry: $(AZURE_CONTAINER_REGISTRY)
            repository: "${{ parameters.repository }}-consumer"
            dockerfile: "sources/back/Franz.Backend/Consumer/Dockerfile"
            buildContext: "sources/back/Franz.Backend/Consumer"
            tags: |
              ${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}
