stages:
  - apply

terraform-apply:
  stage: apply
  image: hashicorp/terraform:1.5.0
  variables:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"
    AWS_REGION: $AWS_REGION
    KAFKA_CLUSTER_NAME: $KAFKA_CLUSTER_NAME
    RABBITMQ_BROKER_NAME: $RABBITMQ_BROKER_NAME
  before_script:
    - apk add --no-cache aws-cli bash
    - cd ${WORKING_DIR}
  script:
    - |
      set -euo pipefail

      echo "🔎 Checking if Kafka Hub already exists..."
      EXISTING_KAFKA=$(aws kafka list-clusters \
        --region "${AWS_REGION}" \
        --query "ClusterInfoList[?ClusterName=='${KAFKA_CLUSTER_NAME}'].ClusterName" \
        --output text || true)

      if [ -n "$EXISTING_KAFKA" ]; then
        echo "✅ Kafka Hub already exists: $EXISTING_KAFKA"
        KAFKA_EXISTS=true
      else
        echo "ℹ️ Kafka Hub does not exist. It will be created."
        KAFKA_EXISTS=false
      fi

      echo "🔎 Checking if RabbitMQ broker already exists..."
      EXISTING_RABBIT=$(aws mq list-brokers \
        --region "${AWS_REGION}" \
        --query "BrokerSummaries[?BrokerName=='${RABBITMQ_BROKER_NAME}'].BrokerName" \
        --output text || true)

      if [ -n "$EXISTING_RABBIT" ]; then
        echo "✅ RabbitMQ broker already exists: $EXISTING_RABBIT"
        RABBIT_EXISTS=true
      else
        echo "ℹ️ RabbitMQ broker does not exist. It will be created."
        RABBIT_EXISTS=false
      fi

      # -------------------------------
      # ✅ Conditional Terraform Apply
      # -------------------------------
      if [ "$KAFKA_EXISTS" = "true" ] && [ "$RABBIT_EXISTS" = "true" ]; then
        echo "⏩ Skipping Terraform apply (Kafka & RabbitMQ already exist)."
      else
        echo "🚀 Running terraform apply..."
        terraform apply -auto-approve tfplan
      fi
  dependencies:
    - terraform-plan   # consume tfplan artifact from plan job
  artifacts:
    when: always
    paths:
      - ${WORKING_DIR}/terraform-apply.log
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
