trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform-infra/**  # Only trigger if Terraform files change

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)   # Stored in Azure DevOps secrets
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)  # Stored in Azure DevOps secrets

stages:
  - stage: DeployInfrastructure
    displayName: "Deploy AWS Infrastructure"
    jobs:
      - job: TerraformDeployment
        displayName: "Terraform Infrastructure Deployment"
        steps:
          # ✅ Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.5.0'

          # ✅ Authenticate with AWS using Azure DevOps secrets
          - script: |
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set region $(AWS_REGION)
            displayName: "Authenticate with AWS"

          # ✅ Terraform Init (Remote State with S3 & DynamoDB)
          - script: |
              terraform init
            displayName: "Initialize Terraform Backend (S3)"

          # ✅ Terraform Validate (Ensure correctness)
          - script: |
              terraform validate
            displayName: "Validate Terraform Configuration"

          # ✅ Terraform Plan (Show what will change)
          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

          # ✅ Terraform Apply (Deploy AWS infrastructure)
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
