trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform-infra/**  # Only trigger if Terraform files change

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)   # Stored in Azure DevOps secrets
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)  # Stored in Azure DevOps secrets

stages:
  - stage: DeployInfrastructure
    displayName: "Deploy AWS Infrastructure"
    jobs:

      # ========================================
      # ✅ 1. Terraform Initialization
      # ========================================
      - job: Terraform_Init
        displayName: "Terraform Init"
        steps:
          - template: jobs/terraform-init.yml  # Calls the separate job file

      # ========================================
      # ✅ 2. Terraform Validate
      # ========================================
      - job: Terraform_Validate
        displayName: "Terraform Validate"
        dependsOn: Terraform_Init
        steps:
          - template: jobs/terraform-validate.yml

      # ========================================
      # ✅ 3. Terraform Plan
      # ========================================
      - job: Terraform_Plan
        displayName: "Terraform Plan"
        dependsOn: Terraform_Validate
        steps:
          - template: jobs/terraform-plan.yml

      # ========================================
      # ✅ 4. Terraform Apply
      # ========================================
      - job: Terraform_Apply
        displayName: "Terraform Apply"
        dependsOn: Terraform_Plan
        steps:
          - template: jobs/terraform-apply.yml
