trigger: none  # 🔥 Prevent auto-trigger, run manually

parameters:
  - name: repository
    displayName: "Repository Name"
    type: string
    default: "Franz"

  - name: serviceName
    displayName: "Microservice Name"
    type: string
    default: "microservice"

  - name: awsEcrUrl
    displayName: "AWS ECR URL"
    type: string
    default: "<AWS_ECR_URL>"  # 🔥 Replace with your actual AWS ECR registry

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

stages:
# ========================================
# ✅ BUILD & PUSH DOCKER IMAGE
# ========================================
  - stage: BuildAndPushDocker
    displayName: "Build & Push Docker Image"
    jobs:
      - job: BuildDocker
        displayName: "Build and Push to AWS ECR"
        steps:
          - script: |
              echo "Logging in to AWS ECR..."
              aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin ${{ parameters.awsEcrUrl }}

              echo "Building Docker image..."
              docker build -t ${{ parameters.serviceName }}:latest .

              echo "Tagging Docker image..."
              docker tag ${{ parameters.serviceName }}:latest ${{ parameters.awsEcrUrl }}/${{ parameters.serviceName }}:latest

              echo "Pushing Docker image to AWS ECR..."
              docker push ${{ parameters.awsEcrUrl }}/${{ parameters.serviceName }}:latest
            displayName: "Build & Push Docker Image"

# ========================================
# ✅ DEPLOY MICROSERVICE TO AWS ECS
# ========================================
  - stage: DeployMicroservice
    displayName: "Deploy to AWS"
    dependsOn: BuildAndPushDocker
    jobs:
      - job: DeployToECS
        displayName: "Deploy to AWS ECS"
        steps:
          - script: |
              echo "Deploying service ${{ parameters.serviceName }} to ECS..."
              aws ecs update-service --cluster ecs-${{ parameters.repository }}-cluster \
                --service ${{ parameters.serviceName }}-service \
                --force-new-deployment
            displayName: "Deploy to ECS"
