trigger: none  # 🔥 Prevent auto-trigger, run manually

parameters:
  - name: repository
    displayName: "Repository Name"
    type: string
    default: "Franz"

  - name: serviceName
    displayName: "Microservice Name"
    type: string
    default: "microservice"

  - name: awsEcrUrl
    displayName: "AWS ECR URL"
    type: string
    default: "<AWS_ECR_URL>"  # 🔥 Replace with actual AWS ECR registry

  - name: deployToEKS
    displayName: "Deploy to EKS (true) or ECS (false)"
    type: boolean
    default: false

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AWS_Variables  # ✅ Load AWS environment variables from DevOps Library

stages:
# ========================================
# ✅ BUILD & PUSH DOCKER IMAGE TO AWS ECR
# ========================================
  - stage: BuildAndPushDocker
    displayName: "Build & Push Docker Image"
    jobs:
      - job: BuildDocker
        displayName: "Build and Push to AWS ECR"
        steps:
          - template: jobs/docker-build-aws.yml
            parameters:
              serviceName: ${{ parameters.serviceName }}
              awsEcrUrl: ${{ parameters.awsEcrUrl }}

# ========================================
# ✅ DEPLOY MICROSERVICE TO AWS ECS or EKS
# ========================================
  - stage: DeployMicroservice
    displayName: "Deploy to AWS"
    dependsOn: BuildAndPushDocker
    jobs:
      - job: DeployToEKS
        condition: eq(${{ parameters.deployToEKS }}, true)
        displayName: "Deploy to EKS"
        steps:
          - template: jobs/deploy-eks.yml
            parameters:
              serviceName: ${{ parameters.serviceName }}

      - job: DeployToECS
        condition: eq(${{ parameters.deployToEKS }}, false)
        displayName: "Deploy to ECS"
        steps:
          - template: jobs/deploy-ecs.yml
            parameters:
              serviceName: ${{ parameters.serviceName }}
