jobs:
- job: docker-build
  displayName: "Docker Build & Push"
  dependsOn: terraform-apply
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - checkout: self

    - task: Docker@2
      displayName: "Login to AWS ECR"
      inputs:
        command: login
        containerRegistry: "$(awsEcrRegistry)"

    - task: Docker@2
      displayName: "Build Docker Image"
      inputs:
        command: build
        repository: "${{ parameters.repository }}"
        dockerfile: "sources/back/Franz.Api/Dockerfile"
        buildContext: "sources/back/Franz.Api"
        tags: |
          $(Build.BuildId)
          latest   # ✅ Optional: always push a latest tag for dev convenience

    - task: Docker@2
      displayName: "Push Docker Image to AWS ECR"
      inputs:
        command: push
        repository: "${{ parameters.repository }}"
        tags: |
          $(Build.BuildId)
          latest
