jobs:
- job: terraform-plan
  displayName: "Terraform Plan"
  dependsOn: terraform-init
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - checkout: self

    - script: |
        echo "Running Terraform Plan for environment: $(environment)"
        terraform plan \
          -var-file="terraform-$(environment).tfvars" \
          -out=tfplan \
          -input=false
      displayName: "Generate Terraform Plan"
