jobs:
- job: Terraform_Validate
  displayName: "Terraform Validate"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - checkout: self   # ✅ Correct way to checkout repo

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.5.0'

    - script: |
        echo "Validating Terraform configuration in $(System.DefaultWorkingDirectory)/Terraform-GCP"
        terraform validate
      displayName: "Validate Terraform Configuration"
      workingDirectory: Terraform-GCP
