# ==========================
# ✅ Prevent Auto-Triggers
# ==========================
pr: none
trigger: none   # Prevent automatic runs; only manual or scheduled

# ==========================
# ✅ Parameters
# ==========================
parameters:
  - name: databaseType
    displayName: "Database Type"
    type: string
    default: "single"
    values: [ single, multi ]

  - name: eventStorageType
    displayName: "Event Storage Type (Only for Multi-DB)"
    type: string
    default: "Kafka"
    values: [ Kafka, CosmosDB, MongoDB ]

  - name: entityStorageType
    displayName: "Entity Storage Type"
    type: string
    default: "SQLServer"
    values: [ PostgreSQL, MariaDB, MySQL, SQLServer, Oracle ]

  - name: messagingType
    displayName: "Messaging Layer"
    type: string
    default: "Kafka"
    values: [ Kafka, RabbitMQ, Both, None ]

  - name: environment
    displayName: "Target Environment"
    type: string
    default: "dev"
    values: [ dev, staging, prod ]

# ==========================
# ✅ Global Variables
# ==========================
variables:
  # 👇 Environment-specific variable group (AWS-Dev, AWS-Prod, etc.)
  - group: AWS-${{ parameters.environment }}
  - name: TF_VERSION
    value: "1.9.6"          # Pin Terraform version
  - name: WORKING_DIR
    value: "infra/aws"      # Path to Terraform root module

# ==========================
# ✅ Stages
# ==========================
stages:
  - stage: DeployInfrastructure
    displayName: "🚀 Deploy AWS Infrastructure"
    jobs:

      # ----------------------------
      # ✅ 1. Terraform Initialization
      # ----------------------------
      - job: Terraform_Init
        displayName: "Terraform Init"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseTerraform@0
            displayName: "Install Terraform ${{ variables.TF_VERSION }}"
            inputs:
              terraformVersion: ${{ variables.TF_VERSION }}

          - template: jobs/terraform-init.yml
            parameters:
              workingDirectory: ${{ variables.WORKING_DIR }}

      # ----------------------------
      # ✅ 2. Terraform Validate
      # ----------------------------
      - job: Terraform_Validate
        displayName: "Terraform Validate"
        dependsOn: Terraform_Init
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: jobs/terraform-validate.yml
            parameters:
              workingDirectory: ${{ variables.WORKING_DIR }}

      # ----------------------------
      # ✅ 3. Terraform Plan
      # ----------------------------
      - job: Terraform_Plan
        displayName: "Terraform Plan"
        dependsOn: Terraform_Validate
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: jobs/terraform-plan.yml
            parameters:
              workingDirectory: ${{ variables.WORKING_DIR }}
              databaseType: ${{ parameters.databaseType }}
              eventStorageType: ${{ parameters.eventStorageType }}
              entityStorageType: ${{ parameters.entityStorageType }}
              messagingType: ${{ parameters.messagingType }}
              environment: ${{ parameters.environment }}

          # 📦 Save plan as artifact for traceability
          - publish: $(Build.SourcesDirectory)/terraform.tfplan
            artifact: terraform-plan-${{ parameters.environment }}
            displayName: "📦 Publish Terraform Plan"

      # ----------------------------
      # ✅ 4. Terraform Apply
      # ----------------------------
      - job: Terraform_Apply
        displayName: "Terraform Apply"
        dependsOn: Terraform_Plan
        pool:
          vmImage: ubuntu-latest
        steps:
          # 🔒 Protect Apply with manual approval
          - task: ManualValidation@0
            displayName: "🔒 Approve Terraform Apply"
            inputs:
              notifyUsers: "devops-team@example.com"
              instructions: "Please review the Terraform Plan artifact before approving Apply."

          - template: jobs/terraform-apply.yml
            parameters:
              workingDirectory: ${{ variables.WORKING_DIR }}
              databaseType: ${{ parameters.databaseType }}
              eventStorageType: ${{ parameters.eventStorageType }}
              entityStorageType: ${{ parameters.entityStorageType }}
              messagingType: ${{ parameters.messagingType }}
              environment: ${{ parameters.environment }}

          # 📤 Capture Outputs
          - script: |
              echo "📤 Capturing Terraform Outputs..."
              terraform output -json > $(Build.ArtifactStagingDirectory)/terraform-outputs.json
            displayName: "📤 Capture Terraform Outputs"

          - publish: $(Build.ArtifactStagingDirectory)/terraform-outputs.json
            artifact: terraform-outputs-${{ parameters.environment }}
            displayName: "📦 Publish Terraform Outputs"
